#!/usr/bin/env python
# -*- coding: utf-8 -*-
""" event_learning.py
Description: Learn network representations of spiking events from intracranial EEG.
"""
__author__ = "Ankit N. Khambhati"
__copyright__ = "Copyright 2021, Ankit N. Khambhati"
__credits__ = ["Ankit N. Khambhati"]
__license__ = ""
__version__ = "1.0.0"
__maintainer__ = "Ankit N. Khambhati"
__email__ = ""
__status__ = "Prototype"


import os
import copy
import joblib
import h5py
import numpy as np
import pandas as pd
import torch
import scipy.stats as sp_stats

from sklearn.cluster import SpectralClustering
from sklearn.metrics import silhouette_score, silhouette_samples
import hashlib
import json

from .torch_seqnmf import SeqNMF, SeqNMFTrainer, parallel_model_update_HW
from .utils import dict_hash

eps = np.finfo(float).resolution


def expand_h5(h5_obj, skip_key=[], axis=0):
    for key in h5_obj:
        if key in skip_key:
            continue

        if isinstance(h5_obj[key], h5py.Group):
            expand_h5(h5_obj[key], skip_key=skip_key, axis=axis)

        if isinstance(h5_obj[key], h5py.Dataset):
            if h5_obj[key].maxshape[axis] is None:
                shape = list(h5_obj[key].shape)
                shape[axis] += 1
                shape = tuple(shape)
                h5_obj[key].resize(shape)


def refresh_h5(h5_obj):
    for key in h5_obj:
        if hasattr(h5_obj[key].id, 'refresh'):
            h5_obj[key].id.refresh()
        else:
            refresh_h5(h5_obj[key])


# MOTIF_SHIFT_SCALER_THRESOLD


class MotifLearning():

    def __init__(self, base_path, mode='r', overwrite=False):
        self.base_path = base_path
        self.model_init = False

        if mode == 'r':
            model_exists = self.setup_path(overwrite=False)
        elif mode == 'a':
            model_exists = self.setup_path(overwrite)
        else:
            raise Exception('Model load mode does not exist.')

        if model_exists:
            self.read_model(mode)
            self.model_init = True
        else:
            print('Model does not exist. Must initialize.')

    def setup_path(self, overwrite):
        self.h5_path = '{}.h5'.format(self.base_path)
        self.obj_path = '{}.obj'.format(self.base_path)

        if overwrite:
            try:
                os.remove(self.h5_path)
            except:
                pass

            try:
                os.remove(self.obj_path)
            except:
                pass

        return os.path.exists(self.h5_path) & os.path.exists(self.obj_path)

    def read_model(self, mode):
        self.h5 = h5py.File(self.h5_path, mode, libver='latest', swmr=True)
        obj = joblib.load(self.obj_path)
        self.params = obj['params']
        self.seqnmf_dict = obj['seqnmf_dict']

    def cache_model(self):
        self.h5.flush()
        joblib.dump(
                {'params': self.params,
                 'seqnmf_dict': self.seqnmf_dict},
                self.obj_path)
        return None

    def update_h5(self):
        for mtype in self.seqnmf_dict:
            for model_i, model in enumerate(self.seqnmf_dict[mtype]['model']):
                for motif_id in range(model.rank):
                    if motif_id >= self.h5[f'{mtype}/motif'].shape[1]:
                        expand_h5(
                            self.h5, skip_key=['LineLength', 'timestamp'], axis=1)

                    self.h5[f'{mtype}/motif'][-1, motif_id] = \
                            model.cnmf.W.detach().numpy()[:, motif_id, :]
                    self.h5[f'{mtype}/coef'][-1, motif_id] = \
                            model.cnmf.H.detach()[0, motif_id, :]

    def init_model(self, params):
        """
        params 
            -> ecog_params
                -> channel_table
                -> n_channel
                -> sampling_frequency
                -> stream_window_size
                -> stream_window_shift
            -> linelength_params
                -> 'squared_estimator
            -> seqnmf_params
                -> model
                    -> convolutional_window_size
                    -> n_motif
                    -> penalties
                        ->
                -> trainer
                    -> motif_lr
                    -> coef_lr
                    -> motif_iter
                    -> coef_iter
                    -> beta
        """
        if self.model_init:
            print('Initialized model may not be re-initialized.')
            return None

        ###
        self.params = params

        ###
        fs = self.params['ecog_params']['sampling_frequency']
        n_chan = self.params['ecog_params']['n_channel']
        stream_winsize = int(self.params['ecog_params']['stream_window_size'] * fs)
         
        ###
        seqnmf_dict = {}
        for model_type in self.params['seqnmf_params']:
            seqnmf_dict[model_type] = {'model': [], 'trainer': []}

            for mt_param in self.params['seqnmf_params'][model_type]:
                seqnmf_winconv = int(
                        mt_param['model']['convolutional_window_size'] * fs)
                n_evwin = stream_winsize - seqnmf_winconv
                
                seqnmf_dict[model_type]['model'].append(
                        SeqNMF(
                            n_chan=n_chan,
                            n_sample=stream_winsize-1,
                            n_convwin=seqnmf_winconv,
                            rank=mt_param['model']['n_motif'],
                            motif_postprocess_params=mt_param['model']['motif_postprocess_params'],
                            coef_postprocess_params=mt_param['model']['coef_postprocess_params'])
                )
                seqnmf_dict[model_type]['trainer'].append(
                        SeqNMFTrainer(
                            seqnmf_dict[model_type]['model'][-1],
                            max_motif_lr=mt_param['trainer']['max_motif_lr'],
                            max_coef_lr=mt_param['trainer']['max_coef_lr'],
                            motif_iter=mt_param['trainer']['motif_iter'],
                            coef_iter=mt_param['trainer']['coef_iter'],
                            beta=mt_param['trainer']['beta'])
                )

        ###
        h5 = h5py.File(self.h5_path, 'w', libver='latest')
       
        #
        h5.create_dataset('timestamp', dtype="f8",
                shape=(0, 2), maxshape=(None, 2))

        #
        h5.create_group("LineLength")
        h5.create_dataset('LineLength/channel_SIG', dtype="f8",
                shape=(1, stream_winsize-1, n_chan),
                maxshape=(1, stream_winsize-1, n_chan))
        
        #
        for mtype in seqnmf_dict:
            h5.create_group(mtype)
            h5.create_dataset(f'{mtype}/motif',
                    dtype="f8",
                    shape=(0, 0, seqnmf_dict[model_type]['model'][0].W.shape[0], seqnmf_dict[model_type]['model'][0].W.shape[-1]),
                    maxshape=(None, None, seqnmf_dict[model_type]['model'][0].W.shape[0], seqnmf_dict[model_type]['model'][0].W.shape[-1]))
            h5.create_dataset(f'{mtype}/coef',
                    dtype="f8",
                    shape=(0, 0, seqnmf_dict[model_type]['model'][0].H.shape[-1]),
                    maxshape=(None, None, seqnmf_dict[model_type]['model'][0].H.shape[-1]))

        h5.swmr_mode = True
        self.h5 = h5
        self.seqnmf_dict = seqnmf_dict
        self.model_init = True

        self.cache_model()

    def measure_linelength(self, signal):
        return np.abs(np.diff(signal, axis=0))

    def update_model(self, signal, pool=None):
        # Compute line-length
        LL = self.measure_linelength(signal['data'])
        if LL is None:
            return True
    
        # MotifSearch
        if np.isfinite(LL).all():
            if (LL > (2*eps)).any():
                
                # SeqNMF Update Models
                (self.seqnmf_dict['MotifSearch']['model'],
                 self.seqnmf_dict['MotifSearch']['trainer']) = \
                     parallel_model_update_HW(
                             self.seqnmf_dict['MotifSearch']['trainer'],
                             LL,
                             pool=pool)

        # MotifSegment
        if np.isfinite(LL).all():
            if (LL > (2*eps)).any():
                
                # SeqNMF Update Models
                (self.seqnmf_dict['MotifSegment']['model'],
                 self.seqnmf_dict['MotifSegment']['trainer']) = \
                     parallel_model_update_HW(
                             self.seqnmf_dict['MotifSegment']['trainer'],
                             self.seqnmf_dict['MotifSearch']['model'][0].signal_resid[:, None].clip(min=0),
                             pool=pool)

        # MotifDiscovery
        if np.isfinite(LL).all():
            if (LL > (2*eps)).any():
                
                # SeqNMF Update Models
                (self.seqnmf_dict['MotifDiscovery']['model'],
                 self.seqnmf_dict['MotifDiscovery']['trainer']) = \
                     parallel_model_update_HW(
                             self.seqnmf_dict['MotifDiscovery']['trainer'],
                             self.seqnmf_dict['MotifSegment']['model'][0].signal_resid[:, None].clip(min=0),
                             pool=pool)

        # Update h5
        expand_h5(self.h5, skip_key=[], axis=0)
        self.h5['timestamp'][-1, 0] = signal['timestamp vector'][0]
        self.h5['timestamp'][-1, 1] = signal['timestamp vector'][-1]
        self.h5['LineLength/channel_SIG'][-1, :, :] = LL
        self.update_h5()
        self.cache_model()
        return True
